[package]
authors = ["Scott Olson <scott@solson.me>"]
name = "rin"
version = "0.3.0"
description = "A cat(1) replacement for humans."
repository = "https://github.com/solson/rin"
license = "MIT"

[dependencies]
clap = "2.6.0"
term = "0.4.4"
